[tool.poetry]
name = "learn_cml"
version = "0.0.1"
description = "Study project"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "*"
numpy = "*"
scikit-learn = "*"
matplotlib = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
