name: Generate report using CML

on: [ push, workflow_dispatch ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: iterative/setup-cml@v2
    - name: Install dependencies, run, test with pytest and  write CML report
      run: |
          pip install -r requirements.txt
          python data_prep_and_train.py
          python predict_and_save.py
          pytest
          
          cat metrics.txt >> report.md
          echo "![](./plot.png)" >> report.md
          cml comment create report.md
